# Generated by Django 5.2.8 on 2025-11-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['tail_number'], 'verbose_name_plural': 'airplanes'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['time'], 'verbose_name_plural': 'locations'},
        ),
    ]
