# Generated by Django 5.2.8 on 2025-11-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_airplane_options_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['tail_number'], 'verbose_name_plural': 'Airplanes'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['time'], 'verbose_name_plural': 'Locations'},
        ),
    ]
