# Generated by Django 5.2.8 on 2025-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_airplane_options_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='airplane',
            name='tail_number',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
