# Generated by Django 5.2.8 on 2025-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_type_alter_airplane_tail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
