# Generated by Django 5.2.8 on 2025-11-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_types'),
        ('api', '0005_alter_type_type'),
    ]

    operations = [
    ]
