# Generated by Django 5.2.8 on 2025-11-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0002_seed_types_0005_alter_type_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type'], 'verbose_name_plural': 'types'},
        ),
    ]
