# Generated by Django 5.2.8 on 2025-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_airplane_tail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='tail_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
