# Generated by Django 5.2.8 on 2025-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_airplane_tail_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Preserve data by coercing the old time value onto a fixed date before
            # flipping the column type to timestamptz. Postgres cannot cast time ->
            # timestamptz directly, hence the explicit USING clause.
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE api_location "
                        "ALTER COLUMN time TYPE timestamp with time zone "
                        "USING timezone('UTC', DATE '1970-01-01' + time);"
                    ),
                    reverse_sql=(
                        "ALTER TABLE api_location "
                        "ALTER COLUMN time TYPE time without time zone "
                        "USING time::time;"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='location',
                    name='time',
                    field=models.DateTimeField(),
                ),
            ],
        ),
    ]
