# Generated by Django 5.2.8 on 2025-11-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_location_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='type_description',
            field=models.CharField(default='NA', max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='altitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='location',
            name='ground_speed',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='location',
            name='track',
            field=models.FloatField(default=-1),
        ),
    ]
