= Problemlösung <Problemlösung>

Im Rahmen der Implementierung ergaben sich verschiedene technische Herausforderungen bezüglich der API-Nutzung, der Szenengestaltung, der Performance und der Datenqualität, die durch gezielte Maßnahmen adressiert wurden.

== API-Ratenbegrenzung und Datenbereinigung
Ein kritischer Aspekt war der Umgang mit der airplanes.live API, die nicht zu aggressiv abgefragt werden darf, um Sperren zu vermeiden. Als Lösung wurde eine künstliche Pause (`sleep`) von einer Sekunde pro abgefragtem Flugzeugtyp sowie ein moderates gesamt-abfrage-Intervall von fünf Minuten eingeführt. Zusätzlich implementierten wir einen Validierungscheck für die Länge der "Tail Number", um fehlerhafte oder unvollständige Datensätze frühzeitig herauszufiltern. Ein weiteres Datenproblem betraf Höhenangaben, die lediglich als "ground" zurückgegeben wurden; diese werden nun systemintern in den numerischen Wert -1 umgewandelt, um sie eindeutig als nicht-fliegende Objekte zu kennzeichnen.

== Marker-Performance
Die Darstellung einer großen Anzahl von Markern führte initial zu spürbaren Einbrüchen der Bildwiederholrate (Framerate). Um die Performance zu stabilisieren, wurde eine konfigurierbare Obergrenze für die Marker-Anzahl sowie eine definierte Lebensdauer eingeführt. Überschüssige Marker werden nun nach dem FIFO-Prinzip (First-In, First-Out) entfernt, sodass stets nur die aktuellsten relevanten Daten visualisiert werden, ohne die Render-Leistung zu überlasten.

== Zeitseriendaten und Visualisierung
Bei der Verarbeitung der zeitbasierten Daten zeigte sich, dass eine Darstellung entsprechend der tatsächlichen Beobachtungszeiträume zu einer extremen zeitlichen Streckung führte. Um die Analyse zu vereinfachen und die visuelle Dichte zu erhöhen, haben wir uns dazu entschlossen, die zeitliche Komponente zu normalisieren und alle in einem Zyklus gesammelten Daten so anzuzeigen, als wären sie zum selben Zeitpunkt aufgetreten.

== Abdeckung der ADS-B Daten
Die Verfügbarkeit der ADS-B Daten ist geografisch stark inkonsistent. Während Nordamerika eine sehr hohe Abdeckung aufweist, ist die Datendichte in Europa bereits geringer und nimmt im globalen Süden sowie in Asien noch weiter ab. Dies lässt sich darauf zurückführen, dass die verwendete ADS-B Datenbank primär durch die Community gespeist wird ("Crowdsourcing"). In Nordamerika ist die Dichte an Hobbyisten, die private ADS-B Empfänger betreiben und Daten einspeisen, schlicht am höchsten, was die geografische Diskrepanz erklären könnte.

== Verfügbarkeit der ADS-B Daten <verfügbarkeit>
ADS-B (Automatic Dependent Surveillance – Broadcast) ist ein Verfahren nach dem vor allem Flugzeuge ungefähr jede Sekunde verschiedene Informationen über sich selbst, wie z.B. Flugnummer, Geschwindigkeit, Flughöhe sowie dazugehörigen Zeitstempel, ungerichtet mittels elektromagnetischem Rundfunk aussenden. Dieser ungerichtete Rundfunk kann von allen aufgefangen und gehört werden, die einen entsprechenden Empfänger besitzen.
Neben offizielen Stellen wie z.B. der amerikanischen FAA (Federal Aviation Administration) existieren mehrere Crowdsourcing Communities wie z.B. ADS-B Exchange @adsbexchange, die die ADS broadcasts empfangen und speichern.
Diese communities stellen meist eine API zur Verfügung über die die von ihnen gespeicherten Daten abgefragt werden können, als Live Daten oder aber auch historisch Datan. Manache verlangen jedoch eine Gebühr für die Nutzung entweder der gesamten API, oder nur der historischen Daten, siehe @adsbexchange. Andere wiederum gewähren erst nach einer Bewerbung in der der Nutzungsgrund erläutert wird und nach eingehender Prüfung dieser einen Zugang zur API, siehe @opensky.
Da wir schnell mit der Entwicklung beginnen wollten, ohne auf eine Genehmigung zu warten oder Kosten zu tragen, haben wir uns letztendlich für den Anbieter Airplanes.LIVE @airplanes-api entschieden, welcher eine kostenlose API zur verfügugn stellt.

== Tracking von Flugzeugen prominenter Personen
Es existieren bereits einige Projekte, die das Flugverhalten von prominenten Personen tracken, wie z.B. celebrityflight.com @clebrityflight oder celebrityprivatejettracker.com @celebrityprivatejettracker. Sie nutzen unter anderem die oben genannten APIs der crowdsourcing Communities @clebrityflight-reddit um die öffentlich zugänglichen Registratiosnnummern der Privatflugzeuge prominenter Personen zu tracken. In Kombination damit, dass z.B. die FAA Details über Flugzeugregistrationen wie z.B. Namen und Adresse des Besitzers öffentlich macht, lassen sich so die Flugdaten und die Personen assoziieren.
Leider war es uns jedoch nciht möglich, das zu verifizieren.
Da wir aufgrund der Kosten und Antragsbarrieren keinen Zugriff auf historische Daten hatten, mussten wir selbst Daten über eine live API sammeln. In diesen Daten konnten wir die Registrationsnummern verschiedener prominenter Personen leider nicht ausmachen. Eine Vermutung unserer Seits ist, dass dies mit einer Maßnahme der FAA zusammen hängt, die es Besitzern privater Flugzeuge erlaubt, ihre Registrations Details aus der öffentlichen Datenbank zu verbergen @block-private-jet-tracking. Zwar sind die crowdgesourcten Projekte wie in @verfügbarkeit bereits erwähnt unabhängig von der FAA, allerdings lässt sich nicht ausschließen, dass diese trotzdem einen Einfluss auf das Sendeverhalten bestimmter Flugzeuge nehmen kann.
Das Problem, dass wir diese spezifischen Flugzeuge nicht tracken konnten brachte uns dazu, dass wir, wie in @Einleitung erwähnt nunmehr nicht mehr die Flugzeuge bestimmter Personen tracken, sondern bestimmte Flugzeugtypen, die am ehesten mit Privatflügen assoziiert werden. Beispielhaft hier z.B. die Gulfstream Reihe @gulfstream.
